### ISSUE TITLE
Radar unlocked twice

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/SeaBlock#296]
Radar is unlocked by both Radars and Military.

**Comment by CornedBee** [comment]
Although this is marked as part of the 0.5.13 milestone and closed as completed, it doesn't seem to have found its way from the dev branch to main and is not actually fixed in 0.5.13.

**Comment by KiwiHawk** [comment]
It's part of 0.5.14 which hasn't been released yet. Main branch should always match what is on the mod portal.
