### ISSUE TITLE
Liquid plastic availability

### ISSUE THREAD

**Issue by Teura** [modded-factorio/SeaBlock#300]
It seems that we get access to plastics & plastic pipes before being able to make liquid plastic. As per the image, the first tech in the circle gives you plastic bars and pipes. But to make liquid plastic, you need any of the three followup techs.

Might be related to an old [issue](https://github.com/modded-factorio/SeaBlock/issues/68), in which plastics from bobs and angels are merged. But looking at the tech names I currently see, they seem separate again. The one in bottom right is "plastic-1", while researched is "plastics"

Tested with all mods from Sea Block Pack, no extras.

![image](https://github.com/modded-factorio/SeaBlock/assets/90751411/0d4ca19f-b330-4394-9a0c-8a265106c39c)

**Comment by KiwiHawk** [comment]
This is working as intended. Not a bug.

There are two different ways of making liquid plastic: bio or petrochem. It's not possible to make Plastics depend on Plastic 1 OR Bio Plastic 1. So we reverse the order of the dependencies.

It might be a bit confusing but I do believe it's the best option we have for now.
